---
title: "Cranial_Measurements_Spatial"
author: "Andrew Laws"
date: "9/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#libraries
library(sf)
library(tmap)
library(tidyverse)
library(readxl)
library(spdep)
library(rgeoda)
library(stringr)
library(gt)
library(webshot)

# crs info
# South Asia Albers Equal Area Conic ESRI: 102028

#India state boundaries
states <- sf::read_sf("../data/orig/india_states_2020.shp") %>% sf::st_make_valid() %>% 
  st_transform(., "ESRI:102028")

 # sri lanka boundary
srla <- sf::read_sf("../data/orig/gadm36_LKA_0.shp") %>% sf::st_make_valid() %>%
  st_transform(., "ESRI:102028") %>% mutate(., NAME = "Sri Lanka", ISO_CODE = "LKA")

#full geometry
aoi <- bind_rows(states, srla) %>%  #rbind would not work due to different column names
  dplyr::select(., c(NAME, ISO_CODE, geometry)) %>%  #clean up tabular data to needed columns
  filter(., ISO_CODE != "INAN") #INAN removed (15 obs) due to physical distance from other polygons impacting analysis

#cranium data
cran <- read_excel("../data/orig/India_Craniometric_Database_All_Data_4_Sept_2013.xlsx", sheet="rdata") %>% 
  dplyr::select(., IndiaState:ISOCODE | Sex:ASB | FOL:ZYB | UFHT:MAB) %>%  #clean up data columns
  filter(., ISOCODE != "INAN") #INAN removed (15 obs) due to physical distance from other polygons impacting analysis

##NOT USED DUE TO UNSURE OF SRI LANKAN GOVERNMENT DATA POLICIES
# bring in sri lanka geometry from AGOL feature service
# library(httr)
# url <- parse_url("https://gisapps.nsdi.gov.lk/server/rest/services")
# url$path <- paste(url$path, "SLNSDI/Boundary/MapServer/7/query", sep = "/")
# url$query <- list(where = "*",
#                   outFields = "*",  
#                   returnGeometry = "true",      
#                   f = "geojson")
# request <- build_url(url)
# https://gisapps.nsdi.gov.lk/server/rest/services/SLNSDI/Boundary/MapServer/7
# srilanka <- st_read(request)
```


```{r EsDA}
# visualize geos
tm_shape(aoi) + tm_polygons(col = "tan")

#cranium factor histograms of factors with values
cran.factors <- dplyr::select(cran, GOL:ASB | FOL:ZYB | UFHT:MAB)

ggplot(gather(cran.factors), aes(value)) + 
    geom_histogram(bins = 10) + 
    facet_wrap(~key, scales = 'free_x')

#get counts of sexes
sexes.count <- cran %>% group_by(Sex) %>% tally()
sexes.count

# counts of observations by ISOCODE
state.count <- cran %>% group_by(ISOCODE) %>% tally()
state.count
```


```{r gol ESDA}
#find gol averages and mean by ISOCODE8
gol.stats <- cran %>% select(ISOCODE, GOL) %>% 
  group_by(ISOCODE) %>% 
  summarise(., GOL.mean = mean(GOL), GOL.median = median(GOL))

#join gol.stats to spatial
gol.sf <- inner_join(aoi, gol.stats, by = c("ISO_CODE" = "ISOCODE")) %>% 
  filter(., ISO_CODE != "INAN") #INAN removed (15 obs) due to physical distance from other polygons

#visualize states that have data
tm_shape(aoi) + tm_polygons(col = "#b9d7f0") + tm_shape(gol.sf) + tm_polygons(col = "red") +
  tm_layout(title = "Study Area (red)")

# # use knn to make up for sri lanka
# gol.nn <- knn2nb(knearneigh(st_centroid(gol.sf), k = 2)) #used 3 neighbors as it showed lowest p-value
# 
# # get list of weights that are row standardized
# gol.lw <- nb2listw(gol.nn, style = "W")
# 
# #moran tests with KNN
# m1 <- moran.test(gol.sf$GOL.mean, gol.lw)
# m2 <- moran.test(gol.sf$GOL.mean, gol.lw)
# moran.test(gol.sf2$GOL.median, gol.lw)

# distance weights
gol.thresh <- min_distthreshold(gol.sf)

gol.dnn <- dnearneigh(st_centroid(gol.sf), d1 = 0, d2 = 1.25 * gol.thresh) #1.25 showed lowest p-values

gol.lw <- nb2listw(gol.dnn, style = "W")

m1 <- moran.test(gol.sf$GOL.mean, gol.lw)
moran.test(gol.sf$GOL.median, gol.lw)

#visualize distance weights
gol.buff <- st_buffer(st_centroid(gol.sf), dist = gol.thresh)

tm_shape(gol.buff) + tm_borders(col = "red") + tm_shape(gol.sf) + tm_polygons()

#local moran
gol.sf$li <- localmoran(gol.sf$GOL.mean, gol.lw)[, 1]

tm_shape(gol.sf) +
  tm_polygons(col = "li")
```

```{r xcb ESDA}
#find xcb averages and mean by ISOCODE8
xcb.stats <- cran %>% select(ISOCODE, XCB) %>% 
  group_by(ISOCODE) %>% 
  summarise(., XCB.mean = mean(XCB), XCB.median = median(XCB))

#join xcb.stats to spatial
xcb.sf <- inner_join(aoi, xcb.stats, by = c("ISO_CODE" = "ISOCODE")) %>% 
  filter(., ISO_CODE != "INAN") #INAN removed (15 obs) due to physical distance from other polygons

# distance weights
xcb.thresh <- min_distthreshold(xcb.sf)

xcb.dnn <- dnearneigh(st_centroid(xcb.sf), d1 = 0, d2 = 1.25 * xcb.thresh) #1.25 showed lowest p-values

xcb.lw <- nb2listwdist(xcb.dnn, st_centroid(xcb.sf), type = "idw", style = "W")

m1 <- moran.test(xcb.sf$XCB.mean, xcb.lw)
m2 <- moran.test(xcb.sf$XCB.mean, xcb.lw)
moran.test(xcb.sf$XCB.median, xcb.lw)

#local moran
xcb.sf$li <- localmoran(xcb.sf$XCB.mean, xcb.lw)[, 1]

tm_shape(xcb.sf) +
  tm_polygons(col = "li")
```

```{r summarize_all}
# summarize all by mean and median
cran.stats <- cran %>% select(., -c(IndiaState, Sex)) %>% 
  group_by(ISOCODE) %>%
  summarise(across(everything(), list(mean=mean, medn=median)))

# join tabluar and spatial data
cran.sf <- inner_join(aoi, cran.stats, by = c("ISO_CODE" = "ISOCODE"))

#calculate min threshold for distance bands
thresh <- rgeoda::min_distthreshold(cran.sf)

#calculate distance weights
cran.lw <- dnearneigh(st_centroid(cran.sf), d1 = 0, d2 = 1.25 * thresh) %>%  #1.25 showed lowest p-values
  nb2listw(., style = "W")

# trying to drop geometry, as cran.sf$GOL_mean =/= cran.sf["GOL_mean"]
# the latter keeps the geometry
cran.df <- st_drop_geometry(cran.sf)

# visualize states with cranium measurements from aoi
tm_shape(aoi) + tm_polygons(col = "tan") +
  tm_shape(cran.sf) + tm_polygons(col = "blue") +
  tm_add_legend(labels = "Geographies with Measurements", col = "blue") +
  tm_layout(title = "Study Area", title.bg.alpha = 0.7, title.bg.color = "white")
```

```{r moran.test}

### This section is where I was walk through error testing from a colleague, Seba ###
# # the error now seems the same but is different, as 
# purrr::map_dfr(cran.sf[4], .f = all.moran) # trows error
# purrr::map_dfr(cran.df[3], .f = all.moran) # works
# # they refer to the same column (GOL_mean)
# 
# # what seems to be missing is an explicit way to remove NAs in the
# # moran function call
# 
# # editing all.moran function
# all.moran_edit <- function(x) {
#   result <- moran.test(x, cran.lw, na.action = na.omit) #run moran test on column
#   stat.name <-  deparse(substitute(x)) #convert column name to string
#   stat <- substr(stat.name, 9, 17) #extract stat name from full column name
#   df <- data.frame("stat"=stat,
#                    "moran" = as.numeric(result$estimate[1]), 
#                    "pval"=as.numeric(result[2]))
#   return(df)
# }
# 
# # testing all columns
# moran.stats <- purrr::map_dfr(cran.df[3:36], .f = all.moran_edit)
# # new error message =  progress! :)
# 
# # checking which column(s) throw an error
# # install.packages("testit")
# test_errors <- tibble("i" = 3:36) %>% 
#   mutate(has_error = purrr::map_lgl(i, function(i){
#     testit::has_error(purrr::map_dfr(cran.df[i], .f = all.moran_edit),
#                       silent = TRUE)
#   })) %>% 
#   filter(has_error)
# # checking which columns produce errors
# test_errors
# 
# # here the culprits
# moran.stats <- purrr::map_dfr(cran.df[15], .f = all.moran_edit)
# moran.stats <- purrr::map_dfr(cran.df[16], .f = all.moran_edit)
# 
# # seems like the error might be related to the moran test,
# 
# # re-editing funciton to fix zero.policy issue (might have to do with islands)
# all.moran_edit2 <- function(x) {
#   result <- moran.test(x, cran.lw, na.action = na.omit, zero.policy = TRUE) #run moran test on column
#   stat.name <-  deparse(substitute(x)) #convert column name to string
#   stat <- substr(stat.name, 9, 17) #extract stat name from full column name
#   df <- data.frame("stat"=stat,
#                    "moran" = as.numeric(result$estimate[1]), 
#                    "pval"=as.numeric(result[2]))
#   return(df)
# }
# 
# # testing function with zero.policy = TRUE
# moran.stats <- purrr::map_dfr(cran.df[3:36], .f = all.moran_edit2)

###return to working script###

# function to calculate moran stats
all.moran <- function(x) {
  result <- moran.test(x, cran.lw, na.action = na.omit, zero.policy = TRUE) #run moran test on column
  
  df <- data.frame("Morans" = round(as.numeric(result$estimate[1]), 3), 
                   "pval"= round(as.numeric(result[2]), 3))
  
  if (df$pval <= 0.05) { #only return statistically significant Moran values
    return(df)
  } 
}

#map function
moran.stats <- purrr::map_dfr(cran.df[3:36], .f = all.moran, .id = "Variable")

moran.stats
```

```{r create moran.stats table, include=FALSE}
#create table
mtest.table <- moran.stats %>% arrange(., pval) %>% 
  gt() %>% 
  tab_header(., 
             title = "Moran.test Values",
             subtitle = "medn suffix equals median") %>% 
  fmt_number(., columns = c("Morans", "pval"),
             decimals = 3)

# export table as png
#requires phantomjs, which is installed using webshot::install_phantonjs()
# mtest.table %>% gtsave(., "morantest.png", path = "../charts")
```

```{r moranmc}
# function for moranmc
all.moranmc <- function(x) {
  result <- moran.mc(x, cran.lw, 10000, na.action = na.omit, zero.policy = TRUE) #run moran mc on column
                                                                                #10,000 iterations used as seen in 
                                                                                #multiple examples from book
  df <- data.frame("Morans" = as.numeric(result$statistic), 
                   "pval"=round(as.numeric(result$p.value), 3))
  
  if (df$pval <= 0.05) { #only return statistically significant Moran values
    return(df)
  } 
}

#map function
moranmc.stats <- purrr::map_dfr(cran.df[3:36], .f = all.moranmc, .id = "Variable")

moranmc.stats
```

```{r create moran.mc table, include=FALSE}
#create table
mmc.table <- moranmc.stats %>% arrange(., pval) %>% #sort least to greatest pval
  gt() %>% 
  tab_header(., 
             title = "Moran.mc Values",
             subtitle = "medn suffix equals median") %>% 
  fmt_number(., columns = c("Morans", "pval"),
             decimals = 3)

# export table as png
#requires phantomjs, which is installed using webshot::install_phantonjs()
# mmc.table %>% gtsave(., "moranmc.png", path = "../charts") #uncomment to export
```

```{r NLH Mean LISA}
#filter out NA's as they interfere with localmoran
NLHmean.sf <- cran.sf %>% filter(., !is.na(NLH_mean)) #don't use drop_na as that removes geometry

# create lw
NLHmean.lw <- dnearneigh(st_centroid(NLHmean.sf), d1 = 0, d2 = 1.25 * thresh) %>%  #1.25 showed lowest p-values
  nb2listw(., style = "W")


#local moran for NLH_mean
NLHmean.sf$NLH_meanLI <- spdep::localmoran(NLHmean.sf$NLH_mean, NLHmean.lw, na.action = na.omit, zero.policy = TRUE)[, 1]

#create map
tm_shape(aoi) + tm_polygons(col = "gray", alpha = 0.3) +
  tm_shape(cran.sf) + tm_polygons(col = "blue") +
  tm_add_legend(labels = "N/A", col = "blue") +
  tm_shape(NLHmean.sf) + tm_polygons(col = "NLH_meanLI", title = "LISA") +
  tm_layout(title = "NLH Mean LISAs", title.bg.color = "white", title.bg.alpha = 0.8)
```

```{r NLH Median LISA}
#filter out NA's as they interfere with localmoran
NLHmedn.sf <- cran.sf %>% filter(., !is.na(NLH_medn)) #don't use drop_na as that removes geometry

# create lw
NLHmedn.lw <- dnearneigh(st_centroid(NLHmedn.sf), d1 = 0, d2 = 1.25 * thresh) %>%  #1.25 showed lowest p-values
  nb2listw(., style = "W")


#local moran for NLH_mean
NLHmedn.sf$NLH_mednLI <- spdep::localmoran(NLHmedn.sf$NLH_medn, NLHmedn.lw, na.action = na.omit, zero.policy = TRUE)[, 1]

#create map
tm_shape(aoi) + tm_polygons(col = "gray", alpha = 0.3) +
  tm_shape(cran.sf) + tm_polygons(col = "blue") +
  tm_add_legend(labels = "N/A", col = "blue") +
  tm_shape(NLHmedn.sf) + tm_polygons(col = "NLH_mednLI", title = "LISA") +
  tm_layout(title = "NLH Median LISAs", title.bg.color = "white", title.bg.alpha = 0.8)
```