---
title: "Lab2"
author: "Andrew Laws"
date: "9/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#libraries
library(tidyverse)
library(tmap)
library(sf)
library(gridExtra)

#data
counties <- sf::read_sf("../data/orig/County_Boundaries.shp") %>% sf::st_make_valid()

dams <- sf::read_sf("../data/orig/Dam_or_Other_Blockage_Removed_2012_2017.shp") %>% sf::st_make_valid()

streams <- sf::read_sf("../data/orig/Streams_Opened_by_Dam_Removal_2012_2017.shp") %>% sf::st_make_valid()

bmps <- read_csv("../data/orig/BMPreport2016_landbmps.csv", show_col_types = FALSE)
```

```{r ESDA, include=FALSE}
glimpse(bmps)

tmap_mode("view")
tm_shape(counties) + tm_polygons(border.col = "green") +
  tm_shape(dams) + tm_dots(col = "red") +
  tm_shape(streams) + tm_lines(col = "blue")

glimpse(dams)
```


# Task 1: Aspatial Operations

### Task 1.1
```{r 1.1}
#group by state then summarize costs and drop any  na field values
task1.1 <- bmps %>% group_by(StateAbbreviation) %>% 
  summarize(stateCost = sum(Cost, na.rm = TRUE))

task1.1
```

### Task 1.2
```{r 1.2}
#log transform skewed data
bmps$logCost <- log(bmps$Cost)
bmps$logTotalAmountCredited <- log(bmps$TotalAmountCredited)

#filter dataset to rows where units are acres and plot log transformed data
task1.2 <- bmps %>% filter(., Unit == "Acres") %>% 
  ggplot(., aes(x=logCost, y=logTotalAmountCredited)) +
  geom_point()
  
task1.2
```

### Task 1.3
```{r 1.3}
#see unique BMPs for cover crops to get idea of spelling
uni.bmps <- c(unique(bmps$BMPShortName))
uni.bmps

#filter BMPShortName to rows with cover in them, checked using uni.bmps
task1.3 <- bmps %>% filter(., stringr::str_detect(BMPShortName, "cover")
                           & TotalAmountCredited > 50 #remove skew from all 0's
                           & TotalAmountCredited < 1000) %>% #makes boxplot more readable
  ggplot(., aes(x=StateAbbreviation, y=TotalAmountCredited)) + #plot
  geom_boxplot()
  
task1.3
```

### Task 1.4

```{r 1.4}
#use filter to remove rows where where year is 0
task1.4 <- dams %>% as_tibble() %>% #convert to tibble for swifter data handling
  filter(., YEAR != 0) %>%  # filter not equal to 0
  ggplot(., aes(x=YEAR, y=STATE)) + #plot
  geom_point(aes(color = OWNER_CODE)) #color by owner code

task1.4
```

### Task 1.5
```{r 1.5}
#sum length of streams per HUC4 code
strm.len <- streams %>% as_tibble() %>% #convert to tibble
  filter(., HUC4 != "0206") %>% #no 0206 dams and stream lenghts are minimal
  group_by(HUC4) %>% #goup by HUC4 code
  summarise(., totLen_KM = sum(LengthKM)) %>%  #sum stream lengths
  ggplot(., aes(x=HUC4, y=totLen_KM)) +
  geom_col(aes(fill = HUC4), show.legend = FALSE) + #don't show legend as legend from dam plot will suffice
  labs(y= "Total Length of Streams (km)",
       caption = "HUC4 code 0206 removed due to lack of dams in basin")

#count of dams per HUC4 code
dam.count <- dams %>% as_tibble() %>% #convert to tibble
  filter(., !is.na(HUC4)) %>% #drop HUC4 is NA
  group_by(HUC4) %>% #group by HUC4 code
  tally() %>%  #tally counts of HUC4
  ggplot(., aes(x=HUC4, y=n)) +
  geom_col(aes(fill = HUC4)) +
  labs(y= "Dam Quantity",
       caption = "No dams recorded in HUC4 0206")

#plot both plots in grid
task1.5 <- gridExtra::grid.arrange(strm.len, dam.count, nrow=1, top = "Correlation between stream length released and number of removed dams")

task1.5
```

# Task 2: Spatial Operations

### Task 2.1
```{r 2.1}
###assume lines have no lengths to make spatial
#check crs of streams to see unit length
st_crs(streams) #length units =  meters

#calculate length of each line in km
streams$len_KM <- as.vector(sf::st_length(streams) / 1000) #1000 m per km

#filter out NA, then sum stream lengths
task2.1 <- streams %>% filter(., !is.na(GNIS_Name)) %>%  #remove NA since we don't know what stream they are from
  group_by(GNIS_Name) %>% #Group by stream name
  summarise(totStreamLen_KM = sum(len_KM)) %>% #sum length per stream
  slice_max(n=5, order_by = totStreamLen_KM) #slice 5 longest streams
  
task2.1
```

### Task 2.2
```{r 2.2}
# intersect streams and counties, groupy by county, sum stream length and slice
task2.2 <- sf::st_intersection(streams, counties) %>% 
  as_tibble() %>%  #convert to tibble for faster processing
  group_by(COUNTYFP10) %>%  # group by county fips code
  summarise(totStrmLen = sum(LengthKM)) %>%  #calculate total stream length per county
  slice_max(n=3, order_by = totStrmLen) 

task2.2
```

